### ISSUE TITLE
ganomede-reward todo list

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede#9]
* [x] specify the module
 * [x] setup ganomede-rewarder worker
 * [x] listen to user connection events
 * [x] post rewards on certain conditions
 * [x] define the "first login" reward (single time reward)
 * [x] remember rewards already sent
deploy
 * [ ] prepare docker
 * [ ] add health check
